services:
  db:
    container_name: sync-calendar-db
    image: postgres:15
    env_file:
      - .env
    ports:
      - '${DB_FORWARD_PORT}:${POSTGRES_PORT}'
    volumes:
      - sync-calendar-db:/var/lib/postgresql/data

  # redis:
  #   container_name: sync-calendar-redis
  #   image: redis:6.2.6
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"
  #   command: redis-server --port ${REDIS_PORT} --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis:/data

  # sync-calendar:
  #   depends_on:
  #     - db
  #   restart: always
  #   container_name: sync-calendar-server
  #   image: mh:sync-calendar
  #   env_file:
  #     - .env
  #   ports:
  #     - '${PORT}:${PORT}'
  #   volumes:
  #     - .:/app
  #     - sync-calendar-public:/app/public
  #     - /app/node_modules

volumes:
  sync-calendar-db:
