services:
  # nginx:
  #   image: nginx:1.25.4-alpine3.18
  #   container_name: starter-nginx
  #   depends_on:
  #     - db
  #     - starter
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./nginx/nestjs-starter.conf.template:/etc/nginx/templates/nestjs-starter.conf.template
  #     - ./nginx/cert:/tmp/cert
  #   restart: always
  #   env_file:
  #     - .env

  db:
    container_name: starter-db
    image: postgres:15
    env_file:
      - .env
    ports:
      - '${DB_FORWARD_PORT}:${POSTGRES_PORT}'
    volumes:
      - starter-db:/var/lib/postgresql/data

  # redis:
  #   container_name: starter-redis
  #   image: redis:6.2.6
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"
  #   command: redis-server --port ${REDIS_PORT} --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis:/data

  starter:
    depends_on:
      - db
    container_name: starter-server
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - starter-public:/app/public
      - /app/node_modules

volumes:
  starter-db:
  starter-public:
