services:
  db:
    container_name: sync-calendar-db
    image: postgres:15
    env_file:
      - .env.stg
    ports:
      - '${DB_FORWARD_PORT}:${POSTGRES_PORT}'
    volumes:
      - sync-calendar-db:/var/lib/postgresql/data

  sync-calendar:
    depends_on:
      - db
    restart: always
    container_name: sync-calendar-server
    image: mh184/sync-calendar
    env_file:
      - .env.stg
    ports:
      - '${PORT}:${PORT}'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 900M
        reservations:
          cpus: 0.5
          memory: 256M
    volumes:
      - ./secret:/app/dist/secret:ro

volumes:
  sync-calendar-db:
