name: Cache Dependencies
description: Cache Dependencies for faster builds
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ env.SERVICE }}-${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn
      shell: bash
