name: 'Build and Test'

on:
  push:
    paths:
      - './**/*'
      - '!.github/workflows/*'
      - .github/workflows/ci.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.11.1

jobs:
  lint:
    # if: false
    name: lint
    runs-on: [self-hosted, linux]
    # defaults:
    #   run:
    #     shell: bash
    #     working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use cache or Install dependencies
        # uses: ./.github/actions/cached-deps-local
        uses: mhieuorg/sdk/.github/actions/cached-deps-local@main

      - name: Lint
        run: yarn lint

  build:
    if: false
    name: build
    # needs: lint
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    env:
      # REGISTRY: ghcr.io
      REGISTRY: reg.mhits.click
      BUILDX_CACHE_DIR: /tmp/.buildx-cache/${{ github.repository }}
      BUILDX_CACHE_NEW_DIR: /tmp/.buildx-cache-new/${{ github.repository }}

    # defaults:
    #   run:
    #     shell: bash
    #     working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Node.js ${{ env.NODE_VERSION }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}

      # - name: Use cache or install Dependencies
      #   uses: ./.github/actions/cached-deps

      # - name: Build
      #   run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry (Docker Hub / Github Registry / Harbor)
        uses: docker/login-action@v3
        with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

          registry: ${{ env.REGISTRY }}
          username: admin
          password: Harbor12345

          # registry: ${{ env.REGISTRY }}
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=local,src=${{ env.BUILDX_CACHE_DIR }}
          cache-to: type=local,mode=max,dest=${{ env.BUILDX_CACHE_NEW_DIR }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

      - name: Move cache
        run: |
          rm -rf ${{ env.BUILDX_CACHE_DIR }}
          mv ${{ env.BUILDX_CACHE_NEW_DIR }} ${{ env.BUILDX_CACHE_DIR }}

      - name: whoami
        run: whoami

  # deploy:
  #   name: deploy
  #   runs-on: [self-hosted, linux]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
